### ISSUE TITLE
CBC is missing

### ISSUE THREAD

**Issue by bmonninkhof** [J0EK3R/fhem-rainbird#1]
I tried to install the module in Them, but maybe I am doing something wrong or ...??

Cannot define RainbirdController device. Perl modul "Crypt::CBC Crypt::Mode::CBC " is missing.

**Comment by bmonninkhof** [comment]
I found a solution on the Fhem forum `sudo cpan install Crypt::CBC`

**Comment by J0EK3R** [comment]
...just in this second i was writing my answear ;)

Yes, you have to install the missing perl modules like you wrote.

I hope you enjoy my module. :)

**Comment by bmonninkhof** [comment]
Hi J0Ek3R, thx for creating the module! I can't test it yet, but will let you know when I do.

> ...just in this second i was writing my answear ;) Yes, you have to install the missing perl modules like you wrote. I hope you enjoy my module. :)
> […](#)
