### ISSUE TITLE
How to connect to Raind Bird LNK-WIFI ?

### ISSUE THREAD

**Issue by dommarion** [J0EK3R/fhem-rainbird#2]
Hello J0EK3R,
I have read all your development, and congrats !
I would like to adapt it to the eedomus box, and to start with I would need some information how to initially connect to the Raind Bird LNK-WIFI ?
If you can explain and help me, I will apply the rest of the package to the eedomus box.
Thanks
Regards,
dommarion

**Comment by J0EK3R** [comment]
Hello dommarion,
I think the code from https://github.com/jbarrancos/pyrainbird - where you also asked for help - would be a better start then mine - my code is very fhem-specific.

I started with that code from pyrainbird, too, and ported it to perl and fhem.

Best greetings
J0EK3R
